### ISSUE TITLE
datasets non-object on fresh run

### ISSUE THREAD

**Issue by simpsus** [tommiehansen/gab#1]
sorry if you don't accept issues. I get 
> Notice: Trying to get property of non-object in /var/www/html/gab/system/class.gab.php on line 119
> Warning: Invalid argument supplied for foreach() in /var/www/html/gab/select.php on line 83

gekko has datasets available in the ui.
At first I thought this was a missing / in the conf.php server variable, but that didn't fix it.

The only thing I have odd in my setup is that I copied gab to /var/www/html.
Using a symlink there and having it in the gekko dir doesn't make a difference though.

Any hint on what this might be?

**Comment by tommiehansen** [comment]
This stricly means that the datasets could not be fetched, thus the 'non-object' since the request didn't answer with one.

This could mean any of the following:
1. Your $server is wrong at system/conf.php and thus it cannot access the datasets.
Default is `http://localhost:3000/api/`
2. You do not have PHP cURL installed and working (thus it can't fetch anything via cURL)
3. You are not running Gekko, so no Gekko API available
4. Something else

**Comment by simpsus** [comment]
Okay, figured it out.
it was a combination that the user owning the gab directory has to have access there and that the trailing slash of the gekko adress is important.
