### ISSUE TITLE
Sending all strategies on POST may cause errors

### ISSUE THREAD

**Issue by tommiehansen** [tommiehansen/gab#15]
Currently the entire form is send but this also include all strategies loaded.

Problem with this is that the user can have strategies that contain exotic values and this can cause things to basically error out.

Changing this behaviour requires the state-saving of strategies to change or that some filter is applied *before* doing the POST requests so that strategy params that will not be used are simply filtered out.

**Comment by tommiehansen** [comment]
Are you sure you actually have Gekko running at http://localhost:3000 ?

**Comment by yepla** [comment]
@tommiehansen I use gab on debian stable with apache2. No errors or anything in the log of apache2 server. And it s heppen on every strategy :(
Note: gekko is running on http://localhost:3000 because gab find exchange history and strategies.
And apaches is running too because i can access gab with strategies and exchange history.
I m so sad it s not work i have all the time the same error on every strategies:
Runner.php ERROR: Running config via curl_post() did not return data.
url: http://localhost:3000/api/backtest | curl status: 500
If you need i do something or give you more information just tell me ...
I really would like use gab to try different parameter when i m backtesting.

**Comment by tommiehansen** [comment]
Last version doesn't send POST-data not needed any longer.

**Comment by yepla** [comment]
@tommiehansen i have upgrade to the last version and still have same error:
Runner.php ERROR: Running config via curl_post() did not return data.
url: http://localhost:3000/api/backtest | curl status: 500
Nothing in apache2 log and /tools/sanitycheck.php says all its ok in green 
...

**Comment by tommiehansen** [comment]
That line is basically critical for the entire application since it's sets the Gekko config object so no -- it does work. It must be something else that is wrong that makes the $gconf wrong and thus error out when sending the curl request etc.

What's the strategy that you're trying to run and how does its TOML-file look? What system are you on?

**Comment by yepla** [comment]
I have tell to you i use linux debian stable and this error happen on all strategies even strategies include in gekko

**Comment by yepla** [comment]
@tommiehansen people on gekko discord channel say to me it have same problem ... to resolve the error they tell me to set one day more of the beginning ...
Now it s work !
for exemple if the import start at 2018-08-17 you need adjust the beginning date by adding a day so here it will be 2018-08-18 and after that gab work ...
Maybe you will need to say it the time you find the bug and fix it

**Comment by tommiehansen** [comment]
I'm aware of that bug, however I'm not obliged to do anything.
I'll create an issue about it though.
