### ISSUE TITLE
Facing issues with getting the setup running

### ISSUE THREAD

**Issue by AdityaNayak** [tommiehansen/gab#16]
Hi @tommiehansen,

First of all, fantastic work with the tool. The UI is just exceptional! 

I am facing issues with getting the setup running. Perhaps you can help me you? This is the errors I see

![image](https://user-images.githubusercontent.com/1292443/38753115-066c552a-3f7b-11e8-8b74-6a5bcb832b03.png)

And 

Warning: Invalid argument supplied for foreach() in /Users/AdityaNayak/Bots/trading/gab/system/class.gab.php on line 63

I have PHP 7.1.2 on mac OS with the latest SQL lite

**Comment by tommiehansen** [comment]
Have you set it up and made sure your settings are 100% correct?
And are you actually running Gekko UI?

It would seem it tries to fetch something that do not exist.

**Comment by AdityaNayak** [comment]
Yes, that was the issue. However, not all issues have been cleared up. 

Can you clarify on where do I see the results?

This is what I see in the log:
![image](https://user-images.githubusercontent.com/1292443/38778512-5723efd8-40d8-11e8-8f2e-450d2a7098e0.png)

and a bunch of errors on the view runs screen. 

![image](https://user-images.githubusercontent.com/1292443/38778520-6bd32476-40d8-11e8-8b1e-7f2815f3bcf0.png)

**Comment by tommiehansen** [comment]
So after 2 hours you got 1 result? You really need to test something else that doesn't require you to run it for 2 hours in order to get a single result.
Also try updating to the last version.
-
Yes, the error for the view is because there is no data to display so there is no `0` in this case. This was fixed a couple of hours ago.
-
Also, in the new version, try running <your install>/tools/ and click on 'Sanity check' and see what it says.

**Comment by AdityaNayak** [comment]
I think the timer doesn't stop when the run gets completed. It showed completed = 1 in under 20 minutes. I am using the standard demo with a variation on candle size to test. 

I am unable to load /tools/ or the view.php page. It just gets stuck at loading. The issue with view page existed earlier also. It does load sporadically though. I don't see any errors in the console.

**Comment by AdityaNayak** [comment]
The /tools/ pages loaded after the run finished. 

I can confirm that I have the latest code from master. 
I also rand the sanity check and it returns everything as ok. 

Is there something else I can do, to be able to get it to run?
Also, this time again. I did a run, it says completed but it doesn't show in the lists of completed runs on the view page.

**Comment by tommiehansen** [comment]
A run can be completed but if it isn't a successful run there is no data to show since the view only shows successful runs.

A "successful" run is defined as a run where your strategy beat the market:

![image](https://user-images.githubusercontent.com/8710941/38779559-634f4766-40ca-11e8-950a-9e83343402c0.png)

**Comment by tommiehansen** [comment]
The user doesn't seem to want to solve the problems.

**Comment by AdityaNayak** [comment]
I appreciate the time taken to arrive at the deduction however, incorrect
and potentially driven by agitation it might be. :)

I have gratitude for you for the effort in building the project, sharing it
and your time you spent in solving this issue.

I'll have bandwidth to only get to this by day after. I'll post the update
incase you are still interested.
