### ISSUE TITLE
Request: Indicate the total number of runs

### ISSUE THREAD

**Issue by simpsus** [tommiehansen/gab#5]
It is easy to misjudge the number of runs you make the system do.
Would it be hard to show how many runs there are in total going to be aside the "completed".

Btw I would be willing to help here. My PHP is rusty at best and I don't know if you are looking for contributions

**Comment by simpsus** [comment]
Thanks for the clarification.
I just felt stupid as it was running for hours and when I checked how many combinations I chose it was 48k. Second mistake is to chose the step smal around the average. That's a weak coverage.

Question: Are the combinations selected randomly? Then it makes sense just to let it beat around the bush until you wanna see some results. I thought it would iterate through all. I am also puzzled by the "already run" messages. That points towards the random running.

**Comment by tommiehansen** [comment]
Yes, the combinations are selected randomly.

Do however note that `random !== random` since there are different algorithms and different levels of "randomness". This is also why i would recommend that people use PHP 7.1+ due to the fact that the `shuffle()` function used to create the random selection was greatly improved in PHP 7.1 with a new and better algorithm (Marsenne Twister).

That's sort of the stuff ordinary people do not see, but it's quite noticable when doing 1000x of something.

See PHP 7.1 update regarding `shuffle()`:
http://php.net/manual/en/function.shuffle.php

**Comment by simpsus** [comment]
Thx for the info.
My server runs PHP 7.1.5. Not that it's my achievement, that seems to be the standard in Ubuntu 17.10. 
I close this issue as you have added it to the todo.

As said before, I would be willing to take a look at it myself. 
I would need pointers on how to setting up a dev environment for this.

**Comment by tommiehansen** [comment]
Oh -- ok. Didn't know that since i usually run the LTS 16.04 or bleeding edge 18+. :)
-
Regarding fixing parts of the code... i'm rewriting most parts of it (mostly non-visual stuff) now so it would be a bit 50/50 since basically all files will change in the next commit (it'll be breaking changes as well; as it says in the README.md this is `alpha` after all).

After that i'd be open for others fixing stuff.
